### ISSUE TITLE
Check for existence in depository.latest_version()

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#124]
Or at least allow it to be None, as some datasets no longer appear to have it?

```Traceback (most recent call last):
 File "fields.py", line 11, in <module>
   version = depo.latest_version()
 File "/Users/irina/.virtualenvs/iterable/lib/python2.7/site-packages/solvebio-1.15.0-py2.7.egg/solvebio/resource/depository.py", line 48, in latest_version
   return self.versions(self['latest_version'].split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split()'```

**Comment by davecap** [comment]
We do still use latest_version, but we also have default_version. We should probably just check for None in the latest_version attribute since sometimes the depository might just not have any versions at all.
