### ISSUE TITLE
Import shortcut isn't playing well with the new capacity argument

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#139]
I'm re-importing an older dataset with the `solvebio import` shortcut in the new python client (that I know should work) and getting the following error

```
Traceback (most recent call last):
  File "/Users/dandan/anaconda2/bin/solvebio", line 11, in <module>
    load_entry_point('solvebio==1.15.2', 'console_scripts', 'solvebio')()
  File "/Users/dandan/anaconda2/lib/python2.7/site-packages/solvebio-1.15.2-py2.7.egg/solvebio/cli/main.py", line 222, in main
    args.func(args)
  File "/Users/dandan/anaconda2/lib/python2.7/site-packages/solvebio-1.15.2-py2.7.egg/solvebio/cli/data.py", line 92, in import_file
    dataset = create_dataset(args)
  File "/Users/dandan/anaconda2/lib/python2.7/site-packages/solvebio-1.15.2-py2.7.egg/solvebio/cli/data.py", line 67, in create_dataset
    capacity=args.capacity,
AttributeError: 'Namespace' object has no attribute 'capacity'
```

**Comment by davecap** [comment]
@dandanxu can you try installing the branch (fix-capacity-arg) and see if that works?

**Comment by jsh2134** [comment]
@dandanxu whats your command....i get a diff error

``` 
$ solvebio import --auto-approve --template-id 391130548592868727 --create-dataset test/test --capacity small ../datas/genes_mirror.json
usage: solvebio [-h] [--version] [--api-host API_HOST] [--api-key API_KEY]
                [--api-token API_TOKEN]
                {shell,create-dataset,logout,import,login,whoami,tutorial} ...
solvebio: error: unrecognized arguments: --capacity
```

**Comment by dandanxu** [comment]
ok, sorry, update -- after `pip uninstall solvebio` multiple times (3x total to get to a real empty state!), I installed this branch and everything works fine. I also tried installing master and that still gave the same Namespace error.

so everything looks good! thank you for the fix

**Comment by davecap** [comment]
Ok great, will post a PR
