### ISSUE TITLE
solvebio login requires quoted arguments

### ISSUE THREAD

**Issue by stevekm** [solvebio/solvebio-python#179]
Following the [guide here](https://docs.solvebio.com/guides/quickstarts/python/), when trying to run the login command, I got error messages unless I put quotes around the username and email address

Error:

```
$ solvebio login
Please enter your SolveBio credentials.
Domain (e.g. <domain>.solvebio.com): stephenkelly
Traceback (most recent call last):
  File "/Users/steve/anaconda3/bin/solvebio", line 11, in <module>
    sys.exit(main())
  File "/Users/steve/anaconda3/lib/python3.6/site-packages/solvebio/cli/main.py", line 236, in main
    return args.func(args)
  File "/Users/steve/anaconda3/lib/python3.6/site-packages/solvebio/cli/auth.py", line 57, in login
    domain, email, password = _ask_for_credentials()
  File "/Users/steve/anaconda3/lib/python3.6/site-packages/solvebio/cli/auth.py", line 28, in _ask_for_credentials
    domain = eval(input('Domain (e.g. <domain>.solvebio.com): '))
  File "<string>", line 1, in <module>
NameError: name 'stephenkelly' is not defined

```

Works when quotes are used:

```
$ solvebio login
Please enter your SolveBio credentials.
Domain (e.g. <domain>.solvebio.com): "stephenkelly"
Email: "my.email@email.com"
Password (typing will be hidden):
You are now logged-in as my.email@email.com.
```

Also, arrow-keys do not work while the program is waiting for user input:

```
$ solvebio login
Please enter your SolveBio credentials.
Domain (e.g. <domain>.solvebio.com): ^[[C^[[C^[[D^[[D^[[C^[[D^[[A^[[C^[[B
```

Using Python 3.6.1 :: Anaconda 4.4.0 (x86_64) & bash 3.2.57

**Comment by davecap** [comment]
Could be a Python 3 thing?

**Comment by stevekm** [comment]
Yes after switching back to Python 2.7 the issues went away.

**Comment by jsh2134** [comment]
Interactive login mode was removed in v2.10
