### ISSUE TITLE
[Upload] Shortcut fails when folder name contains space?

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#201]
renaming the folder to have no spaces or ')' solved the issue

```
ganesha@~/code/solve $ solvebio upload --vault Trials --path=/full_trials  "/Users/ganesha/Downloads/search_result (3)/*"
Traceback (most recent call last):
  File "/usr/local/bin/solvebio", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/solvebio/cli/main.py", line 287, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/site-packages/solvebio/cli/data.py", line 151, in upload
    vault.name)
  File "/usr/local/lib/python2.7/site-packages/solvebio/resource/object.py", line 68, in upload_file
    md5, _ = md5sum(local_path, multipart_threshold=None)
  File "/usr/local/lib/python2.7/site-packages/solvebio/utils/md5sum.py", line 19, in md5sum
    filesize = os.path.getsize(path)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/Users/ganesha/Downloads/search_result (3)/*'

ganesha@~/code/solve $ mv ~/Downloads/search_result\ \(3\) ~/Downloads/full_trials
ganesha@~/code/solve $ solvebio upload --vault Trials --path=/full_trials  "/Users/ganesha/Downloads/full_trials/"
Notice: Folder created for /Users/ganesha/Downloads/full_trials at /full_trials/full_trials
Notice: File created for /Users/ganesha/Downloads/full_trials/NCT00038974.xml at /full_trials/full_trials/NCT00038974.xml
Notice: Upload initialized
Notice: Successfully uploaded /Users/ganesha/Downloads/full_trials/NCT00038974.xml to /full_trials/full_trials/NCT00038974.xml
Notice: File created for /Users/ganesha/Downloads/full_trials/NCT03192215.xml at /full_trials/full_trials/NCT03192215.xml
Notice: Upload initialized
```

**Comment by jsh2134** [comment]
closing this. 

the issue is not the space in the filename, but actually the `*` - the shortcut requires a valid file name, not a glob
