### ISSUE TITLE
[Install] SolveBio install fails with pycurl error re: SSL backend

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#277]
When installing SolveBio on a new Macbook, pycurl fails to detect SSL.

python 3.7 pip3 install and python3

```
Collecting pycurl>=7.0.0 (from solvebio)
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Using curl-config (libcurl 7.54.0)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_1/4mld26ls2hd8tckyjqgj3y2984kkdm/T/pip-install-a8nnqgxq/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/private/var/folders/_1/4mld26ls2hd8tckyjqgj3y2984kkdm/T/pip-install-a8nnqgxq/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/private/var/folders/_1/4mld26ls2hd8tckyjqgj3y2984kkdm/T/pip-install-a8nnqgxq/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/private/var/folders/_1/4mld26ls2hd8tckyjqgj3y2984kkdm/T/pip-install-a8nnqgxq/pycurl/setup.py", line 316, in configure_unix
        specify the SSL backend manually.''')
    __main__.ConfigurationError: Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_1/4mld26ls2hd8tckyjqgj3y2984kkdm/T/pip-install-a8nnqgxq/pycurl/
```

**Comment by jsh2134** [comment]
Workaround is to just do this `PYCURL_SSL_LIBRARY=openssl pip install solvebio` although maybe we can set a default automatically?

**Comment by davecap** [comment]
pycurl is no longer a dependency, closing this.
