### ISSUE TITLE
Failure to upload folders of files containing chinese chars

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#365]
Confirmed that the files can be uploaded via the UI

Stack trace:

```
solvebio upload "REDACTED_FILENAME_WITH_CHINESE_CHARACTERS).csv"
Traceback (most recent call last):
  File "/usr/local/bin/solvebio", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/solvebio/cli/main.py", line 436, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/site-packages/solvebio/cli/data.py", line 343, in upload
    vault.full_path)
  File "/usr/local/lib/python3.7/site-packages/solvebio/resource/object.py", line 305, in upload_file
    obj = cls.get_by_full_path(full_path, client=_client)
  File "/usr/local/lib/python3.7/site-packages/solvebio/resource/object.py", line 170, in get_by_full_path
    **params)
  File "/usr/local/lib/python3.7/site-packages/solvebio/resource/apiresource.py", line 261, in _retrieve_helper
    response = _client.get(url, params)
  File "/usr/local/lib/python3.7/site-packages/solvebio/client.py", line 161, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/solvebio/client.py", line 263, in request
    _handle_api_error(response)
  File "/usr/local/lib/python3.7/site-packages/solvebio/client.py", line 42, in _handle_api_error
    raise SolveError(response=response)
solvebio.errors.SolveError: Unexpected error communicating with SolveBio. If this problem persists, let us know at support@solvebio.com.
```

**Comment by kmendler** [comment]
Some more notes:
1. When uploading a folder via the UI, if one of the containing files contains a special character in its name, the upload sits in PENDING
2. When uploading a folder via the CLI -> get same stacktrace as in Jeff's comment

Thank you for looking into this!

**Comment by jsh2134** [comment]
This was an API backend issue and a fix has been deployed
