### ISSUE TITLE
Dataset/File query raises an error when it has been sliced and a stop param is set to float('inf')

### ISSUE THREAD

**Issue by nikolamaric** [solvebio/solvebio-python#385]
Slicing results of dataset/file query raises an error when `stop` param is set to `float('inf')`, or in other words to the end of the result list.

```
Example:

d = Dataset.retrieve(1390529638872624453)
for i in d.query()[1:]:
    pprint(i)

Result:

{'_commit': '1390529745255123200',
 '_id': 'AXX6NkquZs-hDkFUZ3lY',
 'city': 'Chicago',
 'name': 'Kate',
 'occupation': 'Developer',
 'phonenumber': '(949) 555-6707'}
Traceback (most recent call last):
  File "C:/NikolaM/Projects/SolveBio/Repos/solvebio-python/test_examples/test_archiving_restore.py", line 8, in <module>
    for i in d.query(page_size=1)[1:]:
  File "C:\NikolaM\Projects\SolveBio\Repos\solvebio-python\solvebio\query.py", line 392, in __next__
    return self.next()
  File "C:\NikolaM\Projects\SolveBio\Repos\solvebio-python\solvebio\query.py", line 422, in next
    return self._buffer[self._buffer_idx - 1]
IndexError: list index out of range
```

**Comment by nikolamaric** [comment]
Update: This happens only when a potential chunk of dataset/file records for the query is larger than the number of records that are left in the dataset/file. 

```
# pseudocode
ds  = [1, 2, 3] # only 3 records in the dataset
limit = 10 # default value is 100
for i in ds.query(limit=limit)[1:]:
    print(i)
```

This happens because the `start` param in the slicing is basically SQL `OFFSET` operation.
e.g. `ds.query(limit=limit)[n:] <==> SELECT * FROM table OFFSET <n> LIMIT <limit>`
